version: '2'

services:

  web:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    links:
      - postgres
    environment:
      # NOTE: Change script/setup if you change this value
      DATABASE_URL: postgresql://postgres:password@postgres/crb_development?pool=5

  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
